exercise micro service template added
OnlineTrainingPlatform/Exercises pull request #4
Opened 2022-10-24 12:22 UTC by Dieuer

## Description
-Implement exercise micro service
-Makes use of the template created by Andreas and Freja

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Feature that assists further development (non-breaking change for the developer)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?
*Please describe the tests that you ran to verify your changes*

### Checklist:

- [ ] You have added a clear title and description for the PR
- [ ] The CI pass
- [ ] There are no merge conflicts
- [ ] The code satisfies the [code standards](https://docs.google.com/document/d/1R9n9MeuRwz3WSrnWZUjrbmGeosTlu1Xz8f5F7gu2AJE/edit#heading=h.e9xl4xfoldow) 
- [ ] I have added docstrings for my code, where needed
- [ ] Code implements intended functionality
- [ ] All relevant tests pass (Black, White, Integration, Monkey, etc.)

2022-10-31 14:15 UTC, JakobFaarGreg requested changes
With these changes it looks good to me 👍

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/application/actors/index.ts
> +export * from './user';
What is the reason for doing this?

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/application/actors/user.ts
> +  }
Er der en mulighed for at de her to 'getExerciseUseCase' og  'getExercisesUseCase' på en måde der gør dem lettere genkendelige

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/application/usecases/get_exercises_use_case.spec.ts
> +  it('should return an empty list of exercises if non were found', async () => {
```suggestion
  it('should return an empty list of exercises if none were found', async () => {
```

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/application/usecases/get_exercises_use_case.spec.ts
> +    it('should return an empty list of exercises if non were found', async () => {
```suggestion
    it('should return an empty list of exercises if none were found', async () => {
```

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/application/usecases/get_exercises_use_case.ts
> +  public async do(_: IGetExercisesRequest): Promise<IGetExercisesResponse> {
Ligesom den Github Action siger, hvad har vi brug for parametret til? Hvis vi bare kalder det '_'

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/domain/exercise.spec.ts
> +      expect(() => new Exercise(uuidv4(), '', 'a', [])).toThrow(Error);
This indentation seems weird, can we solve it?

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/domain/exercise.ts
> +    /^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$/gi;
```suggestion
    /^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$/;
```
Vi burde ikke have brug for hverken global match eller case insensitive. Når REGEX er skrevet som det er.
ellers kunne det være: `/^[0-9A-F]{8}\b-[0-9A-F]{4}\b-[0-9A-F]{4}\b-[0-9A-F]{4}\b-[0-9A-F]{12}$/i`

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/domain/query.ts
> +  }
Er det her en oplagt kandidat til at være en switch? Den kunne være nem at extende

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/index.ts
> +// Load the ".env" fiel from the root. Afterwards check all required environment bindings
```suggestion
// Load the ".env" file from the root. Afterwards check all required environment bindings
```

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/infrastructure/mongo_exercise_repository.ts
> +   * @param connection The conenction string to MongoDB
```suggestion
   * @param connection The connection string to MongoDB
```

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/infrastructure/mongo_exercise_repository.ts
> +    // The model adhereing to the document schema
```suggestion
    // The model adhering to the document schema
```

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/infrastructure/mongo_exercise_repository.ts
> +   * @returns All exercises which are stored persistently in MonogDB
```suggestion
   * @returns All exercises which are stored persistently in MongoDB
```

2022-10-31 14:15 UTC, JakobFaarGreg commented on src/presentation/exercise_controller.spec.ts
> +  it('Returns status 200 if we successfully get exercises', async () => {
Nogle steder har i stort forbogstav i jeres tests, andre steder ikke. Skal vi ikke lige vælge en?

2022-11-03 07:42 UTC, Dieuer commented on src/application/actors/index.ts
> +export * from './user';
It exports everything from the "user" file, such that when importing "actors" module we get everything from "user".

2022-11-03 07:45 UTC, Dieuer commented on src/application/usecases/get_exercises_use_case.ts
> +  public async do(_: IGetExercisesRequest): Promise<IGetExercisesResponse> {
Vi skal opfylde interfacet, men vi har ikke brug for den aktuelle parameter.

2022-11-03 07:47 UTC, Dieuer commented on src/domain/query.ts
> +  }
Man kan ikke lave en switch på det.

2022-11-03 07:53 UTC, fatimaosman99 approved these changes

2022-11-03 07:53 UTC, Dieuer commented on src/presentation/exercise_controller.spec.ts
> +  it('Returns status 200 if we successfully get exercises', async () => {
Det er blevet til stort nu

2022-11-03 07:54 UTC, Dieuer commented on src/application/actors/user.ts
> +  }
renamed til get_all_exercises og get_an_exercise

2022-11-03 08:00 UTC, JakobFaarGreg approved these changes
Great work.

2022-11-03 08:00 UTC, merged